<a href="https://colab.research.google.com/github/vishalyadav5451/Google_Colab/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
house_data = {
    "area": [800, 900, 1200, 1500, 700, 850, 1100, 1300, 600, 750, 1000, 1400, 900, 1150, 1600],
    "bedrooms": [2, 2, 3, 3, 1, 2, 3, 3, 1, 2, 2, 3, 2, 3, 4],
    "bathrooms": [1, 2, 2, 3, 1, 1, 2, 2, 1, 1, 2, 3, 2, 2, 3],
    "location": [
        "Jaipur", "Jaipur", "Jaipur", "Jaipur",
        "Ajmer", "Ajmer", "Ajmer", "Ajmer",
        "Kota", "Kota", "Kota", "Kota",
        "Udaipur", "Udaipur", "Udaipur"  ],
    "price": [
        3200000, 3800000, 5200000, 6500000,
        2500000, 3000000, 4800000, 5500000,
        2200000, 2800000, 4200000, 6000000,
        4000000, 5100000, 7200000
    ]
}

In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame(house_data)

In [ ]:
df

    area  bedrooms  bathrooms location    price
0    800         2          1   Jaipur  3200000
1    900         2          2   Jaipur  3800000
2   1200         3          2   Jaipur  5200000
3   1500         3          3   Jaipur  6500000
4    700         1          1    Ajmer  2500000
5    850         2          1    Ajmer  3000000
6   1100         3          2    Ajmer  4800000
7   1300         3          2    Ajmer  5500000
8    600         1          1     Kota  2200000
9    750         2          1     Kota  2800000
10  1000         2          2     Kota  4200000
11  1400         3          3     Kota  6000000
12   900         2          2  Udaipur  4000000
13  1150         3          2  Udaipur  5100000
14  1600         4          3  Udaipur  7200000

In [ ]:
df.isnull().sum()

area         0
bedrooms     0
bathrooms    0
location     0
price        0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   area       15 non-null     int64
 1   bedrooms   15 non-null     int64
 2   bathrooms  15 non-null     int64
 3   location   15 non-null     object
 4   price      15 non-null     int64
dtypes: int64(4), object(1)
memory usage: 612.0+ bytes

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()
df['location'] = le.fit_transform(df['location'])

In [ ]:
df

    area  bedrooms  bathrooms  location    price
0    800         2          1         1  3200000
1    900         2          2         1  3800000
2   1200         3          2         1  5200000
3   1500         3          3         1  6500000
4    700         1          1         0  2500000
5    850         2          1         0  3000000
6   1100         3          2         0  4800000
7   1300         3          2         0  5500000
8    600         1          1         2  2200000
9    750         2          1         2  2800000
10  1000         2          2         2  4200000
11  1400         3          3         2  6000000
12   900         2          2         3  4000000
13  1150         3          2         3  5100000
14  1600         4          3         3  7200000

In [ ]:
x = df.drop('price' , axis =1)
y = df['price']

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.2 , random_state = 42 )

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

X_train = ss.fit_transform(x_train)
X_test = ss.transform(x_test)

In [ ]:
from sklearn.linear_model import LinearRegression
model =LinearRegression()

In [ ]:
model.fit(x_train , y_train)

LinearRegression()

In [ ]:
pred = model.predict(x_test)

In [ ]:
pred

array([2971736.78317204, 6270757.0183156 , 3084959.60969367])

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
print(mean_absolute_error(y_test , pred))
print(mean_squared_error(y_test , pred))
print(r2_score(y_test , pred))

185844.7305979893
38679059021.08916
0.9809149379830152

In [ ]:
print("RMSE:", np.sqrt(mean_squared_error(y_test,pred)))

RMSE: 196669.92403794016

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
rf = RandomForestRegressor(n_estimators=100 , random_state = 42 )

In [ ]:
rf.fit(x_train , y_train)

RandomForestRegressor(random_state=42)

In [ ]:
rf_pred=rf.predict(x_test)

In [ ]:
r2_score(y_test , rf_pred)

0.9935700657894737

In [ ]:
new_house = pd.DataFrame(
    [[1200, 3, 2, 1]],
    columns=["area", "bedrooms", "bathrooms", "location"]
)

price = model.predict(new_house)
print("Predicted Price:", price)

Predicted Price: [5125521.87475006]